// WARNING: This file has automatically been generated on Tue, 23 Sep 2025 17:26:05 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "hnsw_wrapper.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

