// WARNING: This file has automatically been generated on Sun, 22 Feb 2026 20:02:52 CET.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "hnsw_wrapper.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

