// WARNING: This file has automatically been generated on Tue, 23 Sep 2025 22:50:04 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package hnswlib

/*
#include "hnsw_wrapper.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// HNSW type as declared in go-hnswlib/hnsw_wrapper.h:5
type HNSW unsafe.Pointer
