#!/bin/bash
set -e

PLATFORM_DIR="$1"
if [ -z "$PLATFORM_DIR" ]; then
    echo "Usage: $0 <platform_dir>"
    exit 1
fi

BINDINGS_DIR="bindings/bindings"
mkdir -p "$BINDINGS_DIR"

# Extract platform and arch
PLATFORM=$(echo "$PLATFORM_DIR" | cut -d'_' -f1)
ARCH=$(echo "$PLATFORM_DIR" | cut -d'_' -f2)

if [ -f "$BINDINGS_DIR/bindings.go" ]; then
    # Create Linux-specific bindings
    cat > "$BINDINGS_DIR/bindings_linux.go" << 'EOF'
//go:build linux
// +build linux

// WARNING: This file has automatically been generated
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package bindings

/*
#cgo CFLAGS: -I${SRCDIR}/../.. -I${SRCDIR}/../../hnswlib
#cgo linux,amd64 LDFLAGS: ${SRCDIR}/../../build/linux_amd64/libhnsw_wrapper.a -lstdc++
#cgo linux,arm64 LDFLAGS: ${SRCDIR}/../../build/linux_arm64/libhnsw_wrapper.a -lstdc++
#include "wrapper/hnsw_wrapper.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
EOF

    # Create Darwin-specific bindings
    cat > "$BINDINGS_DIR/bindings_darwin.go" << 'EOF'
//go:build darwin
// +build darwin

// WARNING: This file has automatically been generated
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package bindings

/*
#cgo CFLAGS: -I${SRCDIR}/../.. -I${SRCDIR}/../../hnswlib
#cgo darwin,amd64 LDFLAGS: ${SRCDIR}/../../build/darwin_amd64/libhnsw_wrapper.a -lc++
#cgo darwin,arm64 LDFLAGS: ${SRCDIR}/../../build/darwin_arm64/libhnsw_wrapper.a -lc++
#include "wrapper/hnsw_wrapper.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
EOF

    # Extract the Go function definitions from bindings.go (everything after import "C")
    GO_FUNCTIONS=$(sed -n '/import "C"/,$p' "$BINDINGS_DIR/bindings.go" | tail -n +2)
    
    # Append the functions to both platform files
    echo "$GO_FUNCTIONS" >> "$BINDINGS_DIR/bindings_linux.go"
    echo "$GO_FUNCTIONS" >> "$BINDINGS_DIR/bindings_darwin.go"
    
    # Remove the original bindings.go
    rm "$BINDINGS_DIR/bindings.go"
    
    echo "Created platform-specific bindings for Linux and Darwin"
else
    echo "Error: bindings.go not found"
    exit 1
fi
