// WARNING: This file has automatically been generated on Sun, 10 Aug 2025 22:45:22 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "wrapper/hnsw_wrapper.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

