// WARNING: This file has automatically been generated on Mon, 11 Aug 2025 00:07:49 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Go bindings for hnswlib via a thin C wrapper
*/
package bindings
