// WARNING: This file has automatically been generated on Sun, 10 Aug 2025 23:55:27 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Go bindings for hnswlib via a thin C wrapper
*/
package bindings
