// WARNING: This file has automatically been generated on Mon, 11 Aug 2025 00:07:49 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package bindings

/*
#include "wrapper/hnsw_wrapper.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// HNSW type as declared in wrapper/hnsw_wrapper.h:5
type HNSW unsafe.Pointer
