// WARNING: This file has automatically been generated on Sun, 10 Aug 2025 23:55:27 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package bindings

/*
#include "wrapper/hnsw_wrapper.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// HNSW type as declared in wrapper/hnsw_wrapper.h:5
type HNSW unsafe.Pointer
